//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace Techne.Lyceum.RN.ws_SolicitaCartaoSEPI {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SolicitaCartaoSEPISoap", Namespace="http://microsoft.com/webservices/")]
    public class SolicitaCartaoSEPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SolicitaCartaoSEPI() {
            this.Url = "http://172.16.70.129:92/SolicitaCartaoSEPI.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/SolicitaCartaoSEPI_", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CartaoSEPI SolicitaCartaoSEPI_(string CodigoUnidade, string MatriculaLYCEUM, string NomeAluno, System.DateTime DataNascimento, string NumeroRG, string CodigoCurso, string NomeCurso, string Serie, string Turma, string SituacaoAluno, string TipoSolicitacao, string UsuarioSolic) {
            object[] results = this.Invoke("SolicitaCartaoSEPI_", new object[] {
                        CodigoUnidade,
                        MatriculaLYCEUM,
                        NomeAluno,
                        DataNascimento,
                        NumeroRG,
                        CodigoCurso,
                        NomeCurso,
                        Serie,
                        Turma,
                        SituacaoAluno,
                        TipoSolicitacao,
                        UsuarioSolic});
            return ((CartaoSEPI)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSolicitaCartaoSEPI_(string CodigoUnidade, string MatriculaLYCEUM, string NomeAluno, System.DateTime DataNascimento, string NumeroRG, string CodigoCurso, string NomeCurso, string Serie, string Turma, string SituacaoAluno, string TipoSolicitacao, string UsuarioSolic, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SolicitaCartaoSEPI_", new object[] {
                        CodigoUnidade,
                        MatriculaLYCEUM,
                        NomeAluno,
                        DataNascimento,
                        NumeroRG,
                        CodigoCurso,
                        NomeCurso,
                        Serie,
                        Turma,
                        SituacaoAluno,
                        TipoSolicitacao,
                        UsuarioSolic}, callback, asyncState);
        }
        
        /// <remarks/>
        public CartaoSEPI EndSolicitaCartaoSEPI_(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CartaoSEPI)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public class CartaoSEPI {
        
        /// <remarks/>
        public string CodigoUnidade;
        
        /// <remarks/>
        public string Matricula;
        
        /// <remarks/>
        public string MatriculaLYCEUM;
        
        /// <remarks/>
        public string NumeroCartao;
        
        /// <remarks/>
        public int NomeAluno;
        
        /// <remarks/>
        public System.DateTime DataNascimento;
        
        /// <remarks/>
        public string CodigoCurso;
        
        /// <remarks/>
        public string NomeCurso;
        
        /// <remarks/>
        public string Serie;
        
        /// <remarks/>
        public string Turma;
        
        /// <remarks/>
        public string UsuarioSolic;
        
        /// <remarks/>
        public string NumeroRG;
        
        /// <remarks/>
        public string TipoSolicitacao;
        
        /// <remarks/>
        public string SituacaoAluno;
        
        /// <remarks/>
        public string StatusCartao;
        
        /// <remarks/>
        public string Mensagem;
    }
}
